version: '2'
services:
    enigmaui-app:
        image: enigmaui
        external_links:
            - enigmaui-postgresql:postgresql
            # Uncomment to have Cassandra working with the gateway
            # - enigmaui-cassandra:cassandra
            - enigmaui-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
            - SPRING_CLOUD_CONFIG_URI=http://registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/enigmaUI
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    enigmaui-postgresql:
        extends:
            file: postgresql.yml
            service: enigmaui-postgresql
        # Uncomment to have Cassandra working with the gateway
        # extends:
        #     file: cassandra.yml
        #     service: enigmaui-cassandra
    enigmaui-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: enigmaui-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
