version: '2'
services:
    enigmaui-cassandra:
        container_name: enigmaui-cassandra
        build:
            context: .
            dockerfile: cassandra/Cassandra.Dockerfile
        # volumes:
        #     - ~/volumes/jhipster/enigmaUI/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    enigmaui-cassandra-node:
        build:
            context: .
            dockerfile: cassandra/Cassandra.Dockerfile
        links:
            - enigmaui-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
