version: '2'
services:
    enigmaquiz-app:
        image: enigmaquiz
        external_links:
            - enigmaquiz-postgresql:postgresql
            - enigmaquiz-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
            - SPRING_CLOUD_CONFIG_URI=http://registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/enigmaQuiz
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
    enigmaquiz-postgresql:
        extends:
            file: postgresql.yml
            service: enigmaquiz-postgresql
    enigmaquiz-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: enigmaquiz-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
