version: '2'
services:
    enigmaquiz-elasticsearch:
        container_name: enigmaquiz-elasticsearch
        image: elasticsearch:1.7.5
        # volumes:
        #     - ~/volumes/jhipster/enigmaQuiz/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
