version: '2'
services:
    enigmaquiz-postgresql:
        container_name: enigmaquiz-postgresql
        image: postgres:9.5.1
        # volumes:
        #     - ~/volumes/jhipster/enigmaQuiz/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=enigmaQuiz
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
